version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - PYTHONPATH=/app

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
    depends_on:
      - backend
